apiVersion : apps/v1
kind: Deployment
metadata:
  name: siteazureexperts 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: siteazureexperts
  template:
    metadata:
      labels:
        app: siteazureexperts 
    spec:
      containers:
        - name: siteazureexperts 
          image: groffeazuredevops.azurecr.io/siteazureexperts
          env:
            - name: ApplicationInsights__InstrumentationKey
              value: 77d6cba1-31d7-4d54-b3a5-bb56e146a897
          ports:
          - containerPort: 80
